version: '3'
services:
  mysql:
    build: ./mysql
    container_name: mysql
    platform: linux/x86_64
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${TZ}
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - net

  flyway:
    build: ./flyway
    command: sh -c "ls -al && flyway info"
    volumes:
      - ./flyway/sql:/flyway/sql
      - ./flyway/conf:/flyway/conf
    depends_on:
      - mysql
    profiles:
      - flyway
    networks:
      - net

networks:
  net: