name: Verify Helm and Kubectl

on:
  workflow_dispatch:

jobs:
  verify-images:
    name: Verify images for helm and k8s
    runs-on: ubuntu-latest
    container: alpine:3.14 
    steps:
      - name: Verify Helm and Kubectl in Docker
        uses: docker://line/kubectl-kustomize:1.31.0-5.5.0
        with:
          args: |
            sh -c "
              echo 'Running inside Docker image line/kubectl-kustomize:1.31.0-5.5.0';
            "
      - name: Test
        continue-on-error: true
        run: kubectl version --client

  verify-images2:
    name: Verify images for helm and k8s 2
    needs: verify-images
    runs-on: ubuntu-latest
    container: alpine:3.14 
    steps:
      - name: Verify Helm and Kubectl in Docker
        uses: docker://dtzar/helm-kubectl:3.16.4

      - name: Test
        continue-on-error: true
        run: |
          kubectl version --client
          helm version

  verify-images3:
    name: Verify images for helm and k8s 3
    needs: verify-images2
    runs-on: ubuntu-latest
    container: alpine:3.14 
    steps:
      - name: Verify Helm and Kubectl in Docker
        uses: docker://dtzar/helm-kubectl:3.16.4
        with:
          args: |
            sh -c "
              echo 'Running inside Docker image line/kubectl-kustomize:1.31.0-5.5.0';
              kubectl version --client;
              helm version;
            "

  npm-test:
    name: Test npm
    runs-on: ubuntu-latest
    container: alpine:3.14
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Test Node.js
        run: node -v

