name: Verify Helm and Kubectl

on:
  workflow_dispatch:

jobs:
  verify-images3:
    name: Verify images for helm and k8s 3
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          kubectl version --client
          helm version

