name: Uses sample
on:
  workflow_dispatch:
jobs:
  command:
    name: Uses sample
    runs-on: ubuntu-20.04
    #runs-on: self-hosted
    steps:
      - name: Show ubuntu details
        run: |
          echo '::group::CLIツールから出力されたログ'
          echo '::notice title=入力値のチェック::入力値をチェックします'
          echo '::warning::これはwarningのログです'
          echo '::error::これはerrorログです'
          echo '::error title=CLIツールが異常終了しました::エラーが発生したので処理を中断します'
          echo '::endgroup::'
