name: Flayway Container

on:
  workflow_dispatch:
  push:

jobs:
  pre:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout other repository
        uses: actions/checkout@v4

      - name: Build
        run: pwd